### ISSUE TITLE
Frequency = None

### ISSUE THREAD

**Issue by yooitsgreg** [NebraLtd/helium-og#2]
Flashed image to sd card and I can access the local ip diagnostics. Everything looks good but I noticed Frequency = None. Can someone explain where this data point comes from and if it could indicate a potential issue?

**Comment by shawaj** [comment]
@yooitsgreg this doesn't matter. On our Nebra units we split by frequency into different fleets, and this shows what it was "originally"

We are re-working how this displays but it doesn't matter that it says None.

The frequency plan (us915, eu868) etc on the line below is what matters 👍
