### ISSUE TITLE
Original helium hotspot firmware EU versión

### ISSUE THREAD

**Issue by litris** [NebraLtd/helium-og#6]
Hi, I was sent a link to the original helium hotspot firmware from your website but it doesn't work.

The led does not light up but there is connection.

Where can I get the SD image for the original Helium?

Two years ago the SD broke and I replaced it with an image from the Helium website but it no longer exists.  

And I have my Hotspot stopped.

Now there is the version from their website Helium OG 2023 but the led does not light up.

**Comment by shawaj** [comment]
The led will not light up. This is a known issue.

The image works fine
